Test build pipeline

diff --git a/.github/workflows/commit-stage.yml b/.github/workflows/commit-stage.yml
--- a/.github/workflows/commit-stage.yml
+++ b/.github/workflows/commit-stage.yml
@@ -5,45 +5,45 @@ on:
     - cron: '0 0 * * 1'
 
 jobs:
-  build:
-    name: Build and Test ${{ matrix.project }}
-    runs-on: ubuntu-22.04
-    permissions:
-      contents: read
-      security-events: write
-    strategy:
-      fail-fast: false
-      matrix:
-        project: [
-          cnsia/catalog-service,
-          cnsia/config-service,
-        ]
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-      - name: Set up JDK
-        uses: actions/setup-java@v3
-        with:
-          distribution: 'corretto'
-          java-version: '17'
-          cache: gradle
-      - name: Build, unit tests and integration tests
-        run: |
-          cd ${{ matrix.project }}
-          chmod +x gradlew
-          ./gradlew build
-      - name: Code vulnerability scanning
-        uses: anchore/scan-action@v3
-        id: scan
-        with:
-          path: "${{ github.workspace }}"
-          fail-build: false
-          severity-cutoff: high
-      - name: Upload vulnerability report
-        uses: github/codeql-action/upload-sarif@v2
-        if: success() || failure()
-        with:
-          sarif_file: ${{ steps.scan.outputs.sarif }}
+#  build:
+#    name: Build and Test ${{ matrix.project }}
+#    runs-on: ubuntu-22.04
+#    permissions:
+#      contents: read
+#      security-events: write
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        project: [
+#          cnsia/catalog-service,
+#          cnsia/config-service,
+#        ]
+#    steps:
+#      - name: Checkout repository
+#        uses: actions/checkout@v3
+#      - name: Set up JDK
+#        uses: actions/setup-java@v3
+#        with:
+#          distribution: 'corretto'
+#          java-version: '17'
+#          cache: gradle
+#      - name: Build, unit tests and integration tests
+#        run: |
+#          cd ${{ matrix.project }}
+#          chmod +x gradlew
+#          ./gradlew build
+#      - name: Code vulnerability scanning
+#        uses: anchore/scan-action@v3
+#        id: scan
+#        with:
+#          path: "${{ github.workspace }}"
+#          fail-build: false
+#          severity-cutoff: high
+#      - name: Upload vulnerability report
+#        uses: github/codeql-action/upload-sarif@v2
+#        if: success() || failure()
+#        with:
+#          sarif_file: ${{ steps.scan.outputs.sarif }}
   package:
     name: Package and Publish
     if: ${{ github.ref == 'refs/heads/main' }}
@@ -72,7 +72,6 @@ jobs:
       - name: Build container image
         run: |
           cd ${{ matrix.project }}
-          run: echo "$pwd"
           chmod +x gradlew
           ./gradlew bootBuildImage \
             --imageName ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
